variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
stages: 
    - build 
    - test 
build: 
    stage: build 
    script:
        - cd auctionhouse
        - cd backend
        - .\gradlew assemble 
test: 
    stage: test 
    script:
        - cd auctionhouse
        - cd backend
        - .\gradlew test
