variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
    SONARQUBE_TOKEN: sqp_2051831715083c3278c958b67616ea44bd30dc7f
    SONARQUBE_URL: http://localhost:9000/
stages: 
    - build 
    - test 
    - sonarqube
build: 
    stage: build 
    script:
        - cd auctionhouse
        - cd backend
        - .\gradlew assemble 
test: 
    stage: test 
    script:
        - cd auctionhouse
        - cd backend
        - .\gradlew test
sonarqube:
    stage: sonarqube
    script:
        -cd auctionhouse
        -cd backend
        -cd .\gradlew sonar
